name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: bubriks/file-content-checker@master
        with:
            structure: >
                {
                    "Title": [
                        "^# presentation:.*$",
                        "^# essay:.*$",
                        "^# demo:.*$",
                        "^# open-source:.*$",
                        "^# executable tutorial:.*$",
                        "^# course automation:.*$",
                        "^# feedback:.*$"
                    ],
                    "MemberSection": {
                        "SectionTitle": "^## members$",
                        "MemberOne": [
                            {
                                "Name&Email": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                                "GitHub": "^github: https://github.com/[a-z]+$"
                            },
                            {
                                "Name&Email": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                            }
                        ],
                        "MemberTwo": [
                            {
                                "Name&Email": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                                "GitHub": "^github: https://github.com/[a-z]+$"
                            },
                            {
                                "Name&Email": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                            },
                            {}
                        ],
                        "MemberThree": [
                            {
                                "Name&Email": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                                "GitHub": "^github: https://github.com/[a-z]+$"
                            },
                            {
                                "Name&Email": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                            },
                            {}
                        ]
                    },
                    "ProposalSection": "^## proposal$"
                }
            path: "tests/README.md"
      - name: Check outputs and modified files
        run: |
          test "${{ steps.selftest.outputs.result }}" != "1"