name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      json_file: tests/test.json
     
    steps:
      - uses: actions/checkout@master
      
      - name: Match test
        id: matchtest
        uses: bubriks/file-content-checker@master
        with:
            structure: >
                {
                    "title": [
                        "^# presentation:.*$",
                        "^# essay:.*$",
                        "^# demo:.*$",
                        "^# open-source:.*$",
                        "^# executable tutorial:.*$",
                        "^# course automation:.*$",
                        "^# feedback:.*$"
                    ],
                    "member": {
                        "title": "^## members$",
                        "memberOne": [
                            {
                                "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                                "gitHub": "^github: https://github.com/[a-z]+$"
                            },
                            {
                                "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                            }
                        ],
                        "memberTwo": [
                            {
                                "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                                "gitHub": "^github: https://github.com/[a-z]+$"
                            },
                            {
                                "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                            },
                            {}
                        ],
                        "memberThree": [
                            {
                                "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                                "gitHub": "^github: https://github.com/[a-z]+$"
                            },
                            {
                                "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                            },
                            {}
                        ]
                    },
                    "proposal": "^## proposal$"
                }
            path: "tests/README.md"
      - name: Check match test result
        run: |
          test "${{ steps.matchtest.outputs.result }}" != "1"
      
      - name: Wrong contents test
        id: wrongcontentstest
        uses: bubriks/file-content-checker@master
        with:
            structure: >
                {
                    "title": [
                        "^$"
                    ]
                }
            path: "tests/README.md"

        - id: readfile
          run: |
            echo "::set-output name=json::cat ${ env.json_file }"
	
        - name: Check content 1
          uses: bubriks/file-content-checker@master
          with:
            path: "tests/README.md"
            structure: ${ steps.readfile.outputs.json }